### ISSUE TITLE
Add tournament report/export for created tournaments

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#224]
## Is your feature request related to a problem?
US Open is asked for by default during registration. Additional tournaments that can be registered for do not give options for a "US Open Players Report" style of page.

## Describe the feature you'd like to see on the Go Congress Website.
Add feature for displaying report for created tournaments when setting up . When adding the tournament this should generate a page/link on the reports page for an additional report of the same style. Tournament should list players participating and allow for OpenGotha style XML file for download.

## Notes
Add any other information or screenshots about the feature request here.

**Comment by EarthSchlange** [comment]
I am going to try and take a look at this. 

@vash3g Are looking to have a players report for each tournament created? Would the new players report link be placed just under the Admin -> Tournaments section?

![Screenshot from 2021-06-20 16-22-45](https://user-images.githubusercontent.com/5054653/122691329-d36f4c00-d1e3-11eb-9436-01f6dcc7d727.png)

**Comment by vash3g** [comment]
It should be similar to the US Open Players report but for each created tournament. Same format is fine.

**Comment by neagle** [comment]
@EarthSchlange I had planned on doing this, but I don't mind if you want to look at it. For context, in 2018 I added a U.S. Open Players report (which @vash3g mentions) to help the TD that pulled information from the AGA TD List and also offered an export that could be pulled directly into Open Gotha.

![2021-06-21 at 9 15 AM](https://user-images.githubusercontent.com/176993/122768012-31964080-d271-11eb-8c29-ed0557ae4658.png)

![2021-06-21 at 9 17 AM](https://user-images.githubusercontent.com/176993/122768376-889c1580-d271-11eb-98b6-f06f3e27a570.png)

Instead of offering just one report like this for the U.S. Open, we want to have one of these for every tournament. We want to remove the dependency on the method I created for scraping the AGA TD List, which I only created because I didn't know about the API, and use the new method that hits the API directly.

From my perspective, other than emergency items that might come up for Steve, this is the one huge must-have that needs to happen before Congress.
