### ISSUE TITLE
Missing "Tournaments" section for attendees that are not an AGA member

### ISSUE THREAD

**Issue by 0lionelzhang0** [usgo/gocongress#275]
## Summary of the Bug
Attendees that are not an AGA member are no longer able to sign up for tournaments or provide their usernames.

## Steps to Reproduce the Behaviour
**i.e.,**
1. Log in to https://www.gocongress.org/
2. Add an attendee then click "this attendee is not an AGA member"
3. See missing "Tournaments" section

## The Expected Behaviour
Non-AGA members should also see the "Tournaments" section so that they can sign up.

## Screenshots
![missing_section](https://user-images.githubusercontent.com/36424267/125572011-b1703b23-f313-49a2-9df3-7ef394074a7a.png)

**Comment by 0lionelzhang0** [comment]
I just noticed that this was an intentional change from today. However, a large number of pair go players are non-AGA members and the current sign-up process for it relies on the validation of IGS usernames and the "username_igs" field in the attendees csv export.

**Comment by neagle** [comment]
This was based on a misunderstanding on my part. For in-person Congresses, AGA Membership _is_ a requirement for participation in tournaments. I actually didn't realize it wasn't for the online Congress, though that certainly makes sense. I've fixed this change and also updated the message on the initial screen of adding an attendee so that it doesn't claim membership is required. Thanks for bringing this to my attention right away, and I apologize for introducing such a major interruption to registration.

**Comment by etower366i2** [comment]
AGA membership is expected of US players, but not of players from other
countries. This is the same as it is for in- person Congresses.

We'll follow up with Emil today, who should be keeping an eye on this.

Best,
Lisa

Dr. Lisa Scott
Author, Researcher, Historian

**Comment by neagle** [comment]
Thanks for the clarification on that, Lisa -- we haven't been clear about that at all on the website, even with previous Congresses, so it'll be good to clarify the messaging on that. I've updated the add attendee page to reflect the requirement for AGA membership for members of the US. At the moment, the website doesn't do any enforcement of membership in order to register for tournaments -- we'll need to rework the flow of the registration so that we can allow / disallow tournament signups after getting the country from the attendee.

**Comment by 0lionelzhang0** [comment]
Thanks for the quick fix!
