### ISSUE TITLE
add category option for Exactly One Plan

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#40]
Currently, there is a Mandatory option on a category requiring users to select one or more plans from that category.  A second option requiring a user to select exactly one plan from that category would be very useful and reduce registration errors.  During the 2015 Congress registration, a few users have selected more than one room type, a room type and 'No Room', a meal plan and 'No Meal Plan', 'Key Deposit' and no room type.  If this feature were available, I would suggest having one category for room type (including 'No Room'), and a second category for 'Key Deposit' or 'No Key Deposit'.

**Comment by jaredbeck** [comment]
Sounds like a good idea, and shouldn't be too hard to do.  We could also do "Exactly N plans", instead of "Exactly One".  Would a registrar ever want that?

Rex, this would go in `app/forms/registration.rb`, similar to [`validate_mandatory_plan_cats`][1].

[1]: https://github.com/usgo/gocongress/blob/43275df28b4379ceb4d55996aacd7881e49b5452/app/forms/registration.rb#L201

**Comment by rcristal** [comment]
Thanks!

**Comment by rcristal** [comment]
Bump priority.  For 2016.

**Comment by rcristal** [comment]
Done.
